# Generated by Django 4.0.4 on 2022-04-18 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supertype',
            old_name='tpye',
            new_name='type',
        ),
    ]
